CREATE DATABASE tartozasok
	DEFAULT CHARACTER SET utf8
	DEFAULT COLLATE utf8_general_ci;
    
USE tartozasok;

CREATE TABLE Tag(
	id NCHAR(8) NOT NULL PRIMARY KEY,

	nev NVARCHAR(255) NOT NULL,

	jelszo NVARCHAR(255) NOT NULL,

	email NVARCHAR(255) NOT NULL
);


CREATE TABLE Tartozas(

	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,

	ertek INT,

	megnevezes NVARCHAR(255),

	felvetelDate DATETIME DEFAULT NOW(),

	lejaratDate DATETIME,

	ado NCHAR(8) NOT NULL,

	tartozo NCHAR(8) NOT NULL,

	CONSTRAINT FK_T_A FOREIGN KEY (ado) REFERENCES Tag(id) ON UPDATE CASCADE ON DELETE CASCADE,

	CONSTRAINT FK_T_T FOREIGN KEY (tartozo) REFERENCES Tag(id) ON UPDATE CASCADE ON DELETE CASCADE

);